### ISSUE TITLE
Bug:   Bundler::GemNotFound

### ISSUE THREAD

**Issue by MKotori** [kitian616/jekyll-TeXt-theme#237]
**Description**

[from /var/lib/gems/2.5.0/gems/bundler-2.1.2/lib/bundler/resolver.rb:258:in `each'
/var/lib/gems/2.5.0/gems/bundler-2.1.2/lib/bundler/resolver.rb:290:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'jekyll-text-theme' in any of the gem sources listed in your Gemfile. (Bundler::GemNotFound)]

**Steps to Reproduce**

1. Theme install （edit Gemfile ＆ _config.yml ）
2. sudo jekyll serve

**Environment (If Necessary)**

- OS: Github Pages, Windows 10
- Jekyll: Github Pages, 4.0

**Comment by smlcodes** [comment]
Do you found Solution ? im getting same error
