### ISSUE TITLE
Issue running theme on fresh installation (gemspec version)

### ISSUE THREAD

**Issue by agmcleod** [kitian616/jekyll-TeXt-theme#280]
**Description**

After installing the theme, I can't seem to run the jekyll server. Here's the output i'm getting:

```
$ bundle exec jekyll serve
Configuration file: C:/Users/Aaron/Documents/src/agmprojects-com/_config.yml
            Source: C:/Users/Aaron/Documents/src/agmprojects-com
       Destination: C:/Users/Aaron/Documents/src/agmprojects-com/_site
 Incremental build: disabled. Enable with --incremental
      Generating...
       Jekyll Feed: Generating feed for posts
  Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/css/main.scss':
                    Error: File to import not found or unreadable: skins/. on line 1:1 of main.scss >> @import ^
                    ------------------------------------------------
      Jekyll 4.1.1   Please append `--trace` to the `serve` command
                     for any additional information or backtrace.
                    ------------------------------------------------
Traceback (most recent call last):
        29: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<main>'
        28: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
        27: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        26: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        25: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        24: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        23: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        22: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        21: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        20: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        19: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
        18: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        17: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
        16: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
        15: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
        14: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:80:in `process'
        13: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:208:in `render'
        12: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `render_pages'
        11: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `each'
        10: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:524:in `block in render_pages'
         9: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:532:in `render_regenerated'
         8: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:63:in `run'
         7: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:84:in `render_document'
         6: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `convert'
         5: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `reduce'
         4: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `each'
         3: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:102:in `block in convert'
         2: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:185:in `convert'
         1: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/sassc-2.4.0-x64-mingw32/lib/sassc/engine.rb:50:in `render'
main.scss:1: Error: File to import not found or unreadable: skins/. (SassC::SyntaxError)
        on line 1:1 of main.scss
>> @import

   ^
        28: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `<main>'
        27: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/bin/jekyll:23:in `load'
        26: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
        25: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        24: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        23: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        22: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        21: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        20: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        19: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        18: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
        17: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        16: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
        15: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
        14: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
        13: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:80:in `process'
        12: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:208:in `render'
        11: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `render_pages'
        10: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:523:in `each'
         9: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:524:in `block in render_pages'
         8: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/site.rb:532:in `render_regenerated'
         7: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:63:in `run'
         6: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:84:in `render_document'
         5: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `convert'
         4: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `reduce'
         3: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:100:in `each'
         2: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:102:in `block in convert'
         1: from C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:182:in `convert'
C:/Users/Aaron/Documents/src/agmprojects-com/vendor/bundle/ruby/2.7.0/gems/jekyll-sass-converter-2.1.0/lib/jekyll/converters/scss.rb:190:in `rescue in convert': Error: File to import not found or unreadable: skins/. (Jekyll::Converters::Scss::SyntaxError)
        on line 1:1 of main.scss
>> @import

   ^
```

**Steps to Reproduce**

It's a fresh installation, as i'm looking to rebuild my personal site.

1. Installed ruby 2.7.0 as well as msys. Already had mingw
2. Installed jekyll & ran the generator to create the new project
3. Added the theme into the Gemfile, and created the missing template files as displayed under the test/ folder here.
4. Ran `bundle install --path vendor/bundle`
5. `bundle exec jekyll serve`

Can find my full source here: https://github.com/agmcleod/website

**Environment (If Necessary)**

- OS: Windows 10
- Ruby: 2.7.0
- Jekyll: 4.1.1 
- Browser: N/A

**Comment by gurnarok** [comment]
Edit your `_config.yaml`file and add these lines:
```yaml
text_skin: default
highlight_theme: default
```

**Comment by agmcleod** [comment]
@gurnarok that did it, thanks a bunch!
