### ISSUE TITLE
Bug: The jekyll-text-theme theme could not be found

### ISSUE THREAD

**Issue by iclass-cc** [kitian616/jekyll-TeXt-theme#381]
**Description**

/usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/theme.rb:84:in `rescue in gemspec': The jekyll-text-theme theme could not be found. (Jekyll::Errors::MissingDependencyException)
[12](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:12)
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/theme.rb:81:in `gemspec'
[13](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:13)
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/theme.rb:19:in `root'
[14](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:14)
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/theme.rb:12:in `initialize'
[15](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:15)
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:439:in `new'
[16](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:16)
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:439:in `configure_theme'
[17](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:17)
  Logging at level: debug
[18](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:18)
Configuration file: /github/workspace/./_config.yml
[19](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:19)
             Theme: jekyll-text-theme
[20](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:20)
github-pages 223 | Error:  The jekyll-text-theme theme could not be found.
[21](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:21)
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:55:in `config='
[22](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:22)
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/site.rb:[23](https://github.com/iclass-cc/iclass-cc.github.io/runs/5401457647?check_suite_focus=true#step:4:23):in `initialize'
23
	from /usr/local/bundle/gems/jekyll-3.9.0/lib/jekyll/commands/build.rb:30:in `new'

**Environment (If Necessary)**

- Operating System: Ubuntu 20.04.3 LTS

**Comment by iclass-cc** [comment]
remove this line from _config.yml:
**theme: jekyll-text-theme**

**Comment by ishandutta2007** [comment]
@iclass-cc  it works but I dont understand why, if `_config.yml` don't need who does?
[docs](https://kitian616.github.io/jekyll-TeXt-theme/docs/en/quick-start) clearly says to put it in `_config.yml`
