### ISSUE TITLE
Bug: Docker Build

### ISSUE THREAD

**Issue by fhkong** [kitian616/jekyll-TeXt-theme#412]
**Build Docker Failed**

When I build the environment for TeXt Theme with docker, I failed to Step 8/10 RUN bundle install. And I want to know how to fix this bug with docker.

**Steps to Reproduce**

1. Install Docker on my machine. Ubuntu20.04
2. docker run --rm -v "$PWD":/usr/src/app -w /usr/src/app ruby:2.6 bundle install
3. docker-compose -f ./docker/docker-compose.build-image.yml build

When I do step 3, I get into the following trouble.
```shell
Step 8/10 : RUN bundle install
 ---> Running in a1b07add330a
/usr/local/lib/ruby/2.7.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /usr/src/app/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
        from /usr/local/lib/ruby/2.7.0/rubygems.rb:296:in `activate_bin_path'
        from /usr/local/bin/bundle:23:in `<main>'
ERROR: Service 'jekyll-text-theme_dev' failed to build: The command '/bin/sh -c bundle install' returned a non-zero code: 1
```

**Comment by pourmand1376** [comment]
Same error here.
