### ISSUE TITLE
Bug: 安装错误 sass-embedded

### ISSUE THREAD

**Issue by kerwinxu** [kitian616/jekyll-TeXt-theme#437]
**Description**

[Description of the bug]

**Steps to Reproduce**

 bundle install --path vendor/bundle
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set --local path 'vendor/bundle'`, and stop using this flag
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies..........
Using rake 10.5.0
Using bundler 2.3.26
Using concurrent-ruby 1.1.10
Using public_suffix 5.0.1
Using minitest 5.16.3
Using colorator 1.1.0
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using ffi 1.15.5
Using forwardable-extended 2.6.0
Using google-protobuf 3.21.12 (x86_64-linux)
Using gemoji 4.0.1
Using racc 1.6.2
Using rb-fsevent 0.11.2
Using rexml 3.2.5
Using liquid 4.0.3
Using mercenary 0.4.0
Using rouge 4.0.1
Using unicode-display_width 2.3.0
Using safe_yaml 1.0.5
Using jekyll-paginate 1.1.0
Using webrick 1.7.0
Using i18n 1.12.0
Using tzinfo 2.0.5
Using addressable 2.8.1
Using em-websocket 0.5.3
Using pathutil 0.16.2
Using rb-inotify 0.10.1
Using nokogiri 1.13.10 (x86_64-linux)
Using kramdown 2.4.0
Using terminal-table 3.0.2
Using activesupport 7.0.4
Using listen 3.7.1
Using kramdown-parser-gfm 1.1.0
Using html-pipeline 2.14.3
Using jekyll-watch 2.2.1
Installing sass-embedded 1.57.1 with native extensions
It is a security vulnerability to allow your home directory to be world-writable, and bundler cannot continue.
You should probably consider fixing this issue by running `chmod o-w ~` on *nix.
Please refer to https://ruby-doc.org/stdlib-3.1.2/libdoc/fileutils/rdoc/FileUtils.html#method-c-remove_entry_secure for details.
Bundler::PathError: Please fix the world-writable issue with your
/mnt/e/onedrive/project/jekyll-TeXt-theme/vendor/bundle/ruby/3.0.0/gems/sass-embedded-1.57.1
directory
  /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler.rb:338:in `rescue in rm_rf'
  /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler.rb:329:in `rm_rf'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:111:in
`strict_rm_rf'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/rubygems_gem_installer.rb:19:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/source/rubygems.rb:207:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:54:in
`install'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/worker.rb:62:in `apply_func'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/worker.rb:57:in `block in
process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/worker.rb:54:in `process_queue'
/var/lib/gems/3.0.0/gems/bundler-2.3.26/lib/bundler/worker.rb:91:in `block (2 levels)
in create_threads'

An error occurred while installing sass-embedded (1.57.1), and Bundler cannot
continue.

In Gemfile:
  jekyll-text-theme was resolved to 2.2.6, which depends on
    jekyll-feed was resolved to 0.17.0, which depends on
      jekyll was resolved to 4.3.1, which depends on
        jekyll-sass-converter was resolved to 3.0.0, which depends on
          sass-embedded

**Expected behavior**

[What you expected to happen]

**Screenshots (If Necessary)**

[Screenshots to help explain your problem.]

**Environment (If Necessary)**

- OS: wsl2 ubuntu 22.04
- Ruby: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
- Jekyll: [e.g. Github Pages, 3.7.3]
- Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Comment by HuangYin0514** [comment]
same problem

**Comment by lautumn1990** [comment]
在Gemfile文件, 添加`gem "jekyll-sass-converter", "<3.0.0"`, 限制[`jekyll-sass-converter`](https://github.com/jekyll/jekyll-sass-converter#migrate-from-2x-to-3x)自动更新到`3.0.0`, 暂时解决
